version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - '3210:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=Europe/Tallinn
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Tallinn
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
volumes:
  pgdata:
